---
title: Portfolio Website
timezone: America/Los_Angeles
url: https://codytwinton.github.io/portfolio-theme
baseurl: 
exclude:
- README.md
- package.json
- package-lock.json
kramdown:
  show_warnings: true
lang: en
liquid:
  error_mode: strict
  strict_filters: true
permalink: pretty
safe: true
sass:
  style: compressed
strict_front_matter: true
collections:
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: page
author:
  name: Portfolio Website
  twitter: codytwinton
social:
  name: Cody Winton
  links:
  - https://twitter.com/codytwinton
  - https://www.facebook.com/codytwinton
  - https://www.linkedin.com/in/codytwinton
  - https://github.com/codytwinton
twitter:
  username: codytwinton
titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
description: Example portfolio website
image: "/uploads/2018/05/20/example-logo.png"
logo: "/uploads/2018/05/20/example-logo.png"
