---
# Jekyll Settings
title: Portfolio Website
timezone: America/Chicago
url: https://codytwinton.github.io/portfolio-theme/
baseurl: 
# Enable once Forestry supports custom collections_dir
# collections_dir: collections
kramdown:
  show_warnings: true
lang: en
liquid:
  error_mode: strict
  strict_filters: true
  # Enable once certain jekyll extensions, like seo, support without errors
  # strict_variables: true
permalink: pretty
safe: true
sass:
  style: compressed
strict_front_matter: true

# SEO
description: Portfolio Website
author:
  name: Portfolio Website
  twitter: codytwinton
# image: "/uploads/logo.png"
# logo: "/uploads/logo.png"
social:
  name: Portfolio Website
  links:
  - https://twitter.com/codytwinton
  - https://www.facebook.com/codytwinton
  - https://www.linkedin.com/in/codytwinton
  - https://github.com/codytwinton
twitter:
  username: codytwinton

# Collections
collections:
  work:
    title: Work
    output: true

# Defaults for Layouts
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: page
