---
title: Portfolio Website
timezone: America/Los_Angeles
description: Example portfolio website
author:
  name: Portfolio Website
  twitter: codytwinton
favicon: assets/images/favicon.png
ga_tracking_id: ''
image: "/uploads/2018/05/20/example-logo.png"
lang: en
logo: "/uploads/2018/05/20/example-logo.png"
social:
  name: Cody Winton
  links:
  - https://twitter.com/codytwinton
  - https://www.facebook.com/codytwinton
  - https://www.linkedin.com/in/codytwinton
  - https://github.com/codytwinton
twitter:
  username: codytwinton
url: https://codytwinton.github.io/portfolio-theme
baseurl: 
collections:
  work:
    title: Work
    output: true
    permalink: "/portfolio/:name"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- README.md
- package.json
- package-lock.json
kramdown:
  show_warnings: true
liquid:
  error_mode: strict
  strict_filters: true
permalink: pretty
safe: true
sass:
  style: compressed
strict_front_matter: true
titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
copyright: Copyright © 2019 Cody Winton
